SITE_TITLE = 'Tree Recycle'
DRIVER_SITE_TITLE = 'Driver'
ADMIN_SITE_TITLE = 'Admin'
ORGANIZATION_NAME = 'Troops 1564 & 1804'
HOME_PAGE_YEAR = '2023'
HOME_PAGE_TITLE = 'Bainbridge Island'
HOME_PAGE_LEAD = 'Scout Troops 1564 & 1804. Recycling Bainbridge Christmas trees since 1997'
DEFAULT_CITY = 'Bainbridge Island'
DEFAULT_STATE = 'Washington'
DEFAULT_COUNTRY = 'United States'

