SITE_TITLE = 'Tree Recycle'
SITE_PRODUCTION_URL = 'https://www.treerecycle.net'
MAILER_PRODUCTION_DEFAULT_URL_HOST = 'www.treerecycle.net'
DRIVER_SITE_TITLE = 'Driver'
ADMIN_SITE_TITLE = 'Admin'
ORGANIZATION_NAME = 'Troops 1564 & 1804'
HOME_PAGE_YEAR = '2023'
HOME_PAGE_TITLE = 'Bainbridge Island'
HOME_PAGE_LEAD = 'Scout Troops 1564 & 1804. Recycling Bainbridge Christmas trees since 1997'
DEFAULT_CITY = 'Bainbridge Island'
DEFAULT_STATE = 'Washington'
DEFAULT_COUNTRY = 'United States'
STRIPE_DEVELOPMENT_PRICE_ITEM = 'price_1Lxwp5AY1LGWbDshKyepVUDL'
STRIPE_PRODUCTION_PRICE_ITEM = 'price_1M8vYzAY1LGWbDshqoJcAiV9'

