stripe:
  development:
    publishable_key: 'pk_test_...'
    secret_key: 'sk_test_...'
  production:
    publishable_key: 'pk_live_...'
    secret_key: 'sk_live_...'

twilio:
  production:
    account_sid: [account_sid]
    auth_token: [auth_token]
  test:
    account_sid: [account_sid]
    auth_token: [auth_token]

mailer:
  development:
    address: [server address]
    port: 465
    user_name: [user name]
    password: [password]
    authentication: login
    tls: true
    enable_starttls_auto: true

  production:
    address: [server]
    port: 465
    user_name: [user name]

bugsnag:
  api_key: [key]

usps:
  username: [username]

google_maps:
  api_key: [api key]

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: ...
