stripe:
  development:
    publishable_key: 'pk_test_...'
    secret_key: 'sk_test_...'
  production:
    publishable_key: 'pk_live_...'
    secret_key: 'sk_live_...'

mailer:
  development:
    username: [gmail user name]
    password: [gmail password]

usps:
  username: [username]

google_maps:
  api_key: [api key]

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: ...
